on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master') || (github.event_name == 'pull_request') }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: temurin
          cache: maven
      - name: Run Tests
        shell: bash
        run: .github/maven.sh -Pqulice clean verify
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && ((github.ref_type == 'branch' && github.ref_name == 'master') || github.ref_type == 'tag') }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 8 with OSSRH
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: temurin
          cache: maven
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: OSSRH_USERNAME # env variable for username in deploy
          server-password: OSSRH_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Get Version
        id: get-version
        run: echo "::set-output name=version::$(.github/version.sh)"
      - name: Deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          VERSION: ${{ steps.get-version.outputs.version }}
        shell: bash
        run: |
          echo "Deploying Maven version $VERSION..."
          if [[ $VERSION == *"-SNAPSHOT" ]]; then
            if [[ $GITHUB_REF_TYPE != "branch" ]]; then
              echo "... can only deploy SNAPSHOTs from branch, ref was $GITHUB_REF"
              exit 1
            fi
          else
            if [[ $GITHUB_REF_TYPE != "tag" ]]; then
              echo "... can only deploy RELEASEs from tags, ref was $GITHUB_REF"
              exit 1
            fi
            if [[ "v$VERSION" != $GITHUB_REF_NAME ]]; then
              echo "... can only deploy RELEASEs that matches the Maven, expected v$VERSION, ref was $GITHUB_REF"
              exit 1
            fi
          fi
          .github/maven.sh -Prelease clean deploy
